import streamlit as st
import pandas as pd
import pickle

# --- Load the Model ---
model_filename = 'placement_dt_model.pkl'

try:
    with open(model_filename, 'rb') as file:
        model = pickle.load(file)
    st.success(f"Model '{model_filename}' loaded successfully.")
except FileNotFoundError:
    st.error(f"Error: Model file '{model_filename}' not found. Please ensure it's in the same directory as your Streamlit app.")
    st.stop() # Stop the app if the model isn't found
except Exception as e:
    st.error(f"Error loading model: {e}")
    st.stop()

st.title('College Placement Prediction')
st.write('Enter student details to predict placement status.')

# --- Input Features ---
iq = st.slider('IQ', min_value=50, max_value=150, value=100)
# Prev_Sem_Result was dropped from x, so not included here
cgpa = st.slider('CGPA', min_value=0.0, max_value=10.0, value=7.5, step=0.1)
academic_performance = st.slider('Academic Performance (1-10)', min_value=1, max_value=10, value=7)
internship_experience = st.radio('Internship Experience', ['Yes', 'No'])
extra_curricular_score = st.slider('Extra Curricular Score (0-10)', min_value=0, max_value=10, value=5)
communication_skills = st.slider('Communication Skills (1-10)', min_value=1, max_value=10, value=8)
projects_completed = st.slider('Projects Completed', min_value=0, max_value=10, value=3)

# --- Preprocessing User Input ---
# Create a DataFrame from user input
user_input_df = pd.DataFrame({
    'IQ': [iq],
    'CGPA': [cgpa],
    'Academic_Performance': [academic_performance],
    'Extra_Curricular_Score': [extra_curricular_score],
    'Communication_Skills': [communication_skills],
    'Projects_Completed': [projects_completed],
    'Internship_Experience': [internship_experience]
})

# Apply get_dummies for 'Internship_Experience'
# This step must exactly match how you processed the training data in the notebook.
# We used drop_first=True, dtype=int
user_input_processed = pd.get_dummies(user_input_df, columns=['Internship_Experience'], drop_first=True, dtype=int)

# The columns in x_train were: ['IQ', 'CGPA', 'Academic_Performance', 'Extra_Curricular_Score', 'Communication_Skills', 'Projects_Completed', 'Internship_Experience_Yes']
# Ensure all expected columns are present and in the correct order.
# This list must match the columns in your x_train used for model training.
expected_columns = [
    'IQ',
    'CGPA',
    'Academic_Performance',
    'Extra_Curricular_Score',
    'Communication_Skills',
    'Projects_Completed',
    'Internship_Experience_Yes' # This column is generated by get_dummies
]

# Add missing columns with default value 0 (e.g., if 'Internship_Experience_Yes' is not present because input was 'No')
for col in expected_columns:
    if col not in user_input_processed.columns:
        user_input_processed[col] = 0

# Ensure the order of columns is identical to the training data
user_input_final = user_input_processed[expected_columns]

# --- Make Prediction ---
if st.button('Predict Placement'):
    prediction_raw = model.predict(expected_columns)
    prediction_proba = model.predict_proba(expected_columns)

    # Map numerical prediction back to 'Yes'/'No' labels
    prediction_label = 'Yes' if prediction_raw[0] == 1 else 'No'

    st.write(f"### Predicted Placement: {prediction_label}")
    st.write(f"Probability of No Placement: {prediction_proba[0][0]:.2f}")
    st.write(f"Probability of Yes Placement: {prediction_proba[0][1]:.2f}")

    if prediction_label == 'Yes':
        st.success("**Prediction:** This student is likely to get placed!")
    else:
        st.warning("**Prediction:** This student is likely NOT to get placed.")
